# Generated by Django 5.2.8 on 2026-05-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=100)),
                ('st_age', models.IntegerField()),
                ('st_email', models.EmailField(max_length=50)),
                ('st_number', models.IntegerField()),
            ],
        ),
    ]
